# Generated by Django 4.2.3 on 2023-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
